import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
// import localFont from "next/font/local";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // Define a CSS variable for the font
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import React from "react";
import { ComponentsLayout } from "../components/components-layout";
import { ComponentsErrorHandling } from "../components/components-errorhandling";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ComponentsErrorHandling>
          <ComponentsLayout>{children}</ComponentsLayout>
        </ComponentsErrorHandling>
      </body>
    </html>
  );
}
